## Exercise No.3

**1-write program for circle class. This class has the following:**
* Attribute: its name is pi with value 3.14
* During the object create the raduis attribute is asigned by the raduis of circle
* Has two methods to calculate the Area and Circumference of circle

In [83]:
class Circle:
    pi = 3.14
    
    def __init__(self, radius):
        self.radius = radius
    
    def area(self):
        return self.pi * self.radius ** 2
    
    def circumference(self):
        return 2 * self.pi * self.radius

# مثال للاستخدام
circle = Circle(5)
print("مساحة الدائرة:", circle.area())
print("محيط الدائرة:", circle.circumference())

مساحة الدائرة: 78.5
محيط الدائرة: 31.400000000000002


**2. Write a program for a Rectangle class.**

Attributes: length and width (set through constructor)

Methods:

area() – returns the area

perimeter() – returns the perimeter

In [85]:
class Rectangle:
    def __init__(self, length, width):
        self.length = length
        self.width = width
    
    def area(self):
        return self.length * self.width
    
    def perimeter(self):
        return 2 * (self.length + self.width)

# مثال للاستخدام
rect = Rectangle(4, 6)
print("مساحة المستطيل:", rect.area())
print("محيط المستطيل:", rect.perimeter())

مساحة المستطيل: 24
محيط المستطيل: 20


**3-Write a program for an Employee class using class method.**
Attributes: name and salary

Class attribute: company_name

Use a class method to change the company_name for all employees

In [87]:
class Employee:
    company_name = "شركة التقنية"
    
    def __init__(self, name, salary):
        self.name = name
        self.salary = salary
    
    @classmethod
    def change_company(cls, new_name):
        cls.company_name = new_name
    
    def display(self):
        print(f"{self.name} يعمل في {self.company_name} براتب {self.salary}")

# مثال للاستخدام
emp1 = Employee("أحمد", 5000)
emp2 = Employee("محمد", 6000)

emp1.display()
emp2.display()

Employee.change_company("شركة البرمجة الجديدة")

emp1.display()
emp2.display()

أحمد يعمل في شركة التقنية براتب 5000
محمد يعمل في شركة التقنية براتب 6000
أحمد يعمل في شركة البرمجة الجديدة براتب 5000
محمد يعمل في شركة البرمجة الجديدة براتب 6000


**4- Create a Shape class and two child classes Square and Circle.**

Use polymorphism to define a method area()

Use a loop to calculate area for both shapes using a common function

In [89]:
class Shape:
    def area(self):
        pass

class Square(Shape):
    def __init__(self, side):
        self.side = side
    
    def area(self):
        return self.side ** 2

class Circle(Shape):
    def __init__(self, radius):
        self.radius = radius
    
    def area(self):
        return 3.14 * self.radius ** 2

def calculate_area(shape):
    return shape.area()
 
shapes = [Square(4), Circle(5)]

for shape in shapes:
    print("مساحة الشكل:", calculate_area(shape))

مساحة الشكل: 16
مساحة الشكل: 78.5


**5-Create a 1D NumPy array of numbers from 0 to 9**

In [69]:
import numpy as np

arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


**6-Create a 4x4 NumPy array of all True values**

In [71]:
import numpy as np

arr = np.ones((4, 4), dtype=bool)
print(arr)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


**7-Create an array of 10 random floats between 0 and 1**

In [73]:
import numpy as np

arr = np.random.rand(10)
print(arr)

[0.45793777 0.77513271 0.59890477 0.17327077 0.13164529 0.58672169
 0.33601098 0.19899445 0.76683927 0.45866058]


**8-Create a NumPy array of even numbers from 2 to 20**

In [75]:
import numpy as np

arr = np.arange(2, 21, 2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20]


**9-Get the maximum, minimum, and mean of an random array**

In [77]:
import numpy as np

arr = np.random.rand(10)
print("المصفوفة:", arr)
print("القيمة العظمى:", np.max(arr))
print("القيمة الصغرى:", np.min(arr))
print("المتوسط:", np.mean(arr))

المصفوفة: [0.49473552 0.18910637 0.55588472 0.16266525 0.34106587 0.1580862
 0.44408911 0.16056488 0.99193289 0.40047668]
القيمة العظمى: 0.9919328867023604
القيمة الصغرى: 0.1580861970448012
المتوسط: 0.3898607484625602


**10-Flatten a 2D array to 1D**

In [79]:
import numpy as np

arr2d = np.array([[1, 2], [3, 4]])
arr1d = arr2d.flatten()
print("المصفوفة الأصلية:")
print(arr2d)
print("المصفوفة المسطحة:")
print(arr1d)

المصفوفة الأصلية:
[[1 2]
 [3 4]]
المصفوفة المسطحة:
[1 2 3 4]
